#ifndef PROJ_APAK_RADUGA_GLOBAL_H
#define PROJ_APAK_RADUGA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROJ_APAK_RADUGA_SHEKSNA_LIBRARY)
#  define APAK_RADUGA_SHEKSNA_EXPORT Q_DECL_EXPORT
#else
#  define APAK_RADUGA_SHEKSNA_EXPORT Q_DECL_IMPORT
#endif

#endif // PROJ_APAK_RADUGA_GLOBAL_H
