#ifndef ZN_CONNECTION_STATE_GLOBAL_H
#define ZN_CONNECTION_STATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZN_CONNECTION_STATE_LIBRARY)
#  define ZN_CONNECTION_STATE_EXPORT Q_DECL_EXPORT
#else
#  define ZN_CONNECTION_STATE_EXPORT Q_DECL_IMPORT
#endif

#endif // ZN_CONNECTION_STATE_GLOBAL_H
