#ifndef INTERSERVER_EXCHANGE_SENDER_GLOBAL_H
#define INTERSERVER_EXCHANGE_SENDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERSERVER_EXCHANGE_SENDER_LIBRARY)
#  define ISES_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define ISES_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERSERVER_EXCHANGE_SENDER_GLOBAL_H
