#ifndef RADUGA_GLOBAL_STATE_GLOBAL_H
#define RADUGA_GLOBAL_STATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RADUGA_GLOBAL_STATE_LIBRARY)
#  define RADUGA_GLOBAL_STATE_EXPORT Q_DECL_EXPORT
#else
#  define RADUGA_GLOBAL_STATE Q_DECL_IMPORT
#endif

#endif // RADUGA_GLOBAL_STATE_GLOBAL_H
