#ifndef PROJ_12700_GAMMA_OPA_GLOBAL_H
#define PROJ_12700_GAMMA_OPA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERSERVER_EXCHANGE_RECEIVER_LIBRARY)
#  define ISER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define ISER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROJ_12700_GAMMA_OPA_GLOBAL_H
