#ifndef PROJ_12700_OPA_GLOBAL_H
#define PROJ_12700_OPA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROJ_APAK_RADUGA_DATATYPE1_LIBRARY)
#  define APAK_RADUGA_DATATYPE1_EXPORT Q_DECL_EXPORT
#else
#  define APAK_RADUGA_DATATYPE1_EXPORT Q_DECL_IMPORT
#endif

#endif // PROJ_12700_OPA_GLOBAL_H
