#ifndef GAMMA_OPA_IMITATOR_GLOBAL_H
#define GAMMA_OPA_IMITATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAMMA_OPA_IMITATOR_LIBRARY)
#  define GAMMA_OPA_IMITATOR_EXPORT Q_DECL_EXPORT
#else
#  define GAMMA_OPA_IMITATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // GAMMA_OPA_IMITATOR_GLOBAL_H
