#ifndef SUUPORTED_SIGNAL_TAGS
#define SUUPORTED_SIGNAL_TAGS

#include <QObject>
#include <QSet>

#define TAG_MOXA_GLOBAL_STATE "MOXA_GLOBAL_STATE"
#define TAG_MOXA_PORT1_STATE  "MOXA_PORT1_STATE"
#define TAG_MOXA_PORT2_STATE  "MOXA_PORT2_STATE"
#define TAG_MOXA_PORT3_STATE  "MOXA_PORT3_STATE"
#define TAG_MOXA_PORT4_STATE  "MOXA_PORT4_STATE"
#define TAG_MOXA_PORT5_STATE  "MOXA_PORT5_STATE"
#define TAG_MOXA_PORT6_STATE  "MOXA_PORT6_STATE"
#define TAG_MOXA_PORT7_STATE  "MOXA_PORT7_STATE"
#define TAG_MOXA_PORT8_STATE  "MOXA_PORT8_STATE"
#define TAG_MOXA_PORT9_STATE  "MOXA_PORT9_STATE"
#define TAG_MOXA_PORT10_STATE "MOXA_PORT10_STATE"
#define TAG_MOXA_PORT11_STATE "MOXA_PORT11_STATE"
#define TAG_MOXA_PORT12_STATE "MOXA_PORT12_STATE"
#define TAG_MOXA_PORT13_STATE "MOXA_PORT13_STATE"
#define TAG_MOXA_PORT14_STATE "MOXA_PORT14_STATE"
#define TAG_MOXA_PORT15_STATE "MOXA_PORT15_STATE"
#define TAG_MOXA_PORT16_STATE "MOXA_PORT16_STATE"
//#define TAG_
//#define TAG_

namespace apak {

  namespace ups {

    const QSet<QString> SupportedSignalTags = {
      TAG_MOXA_GLOBAL_STATE,
      TAG_MOXA_PORT1_STATE,
      TAG_MOXA_PORT2_STATE,
      TAG_MOXA_PORT3_STATE,
      TAG_MOXA_PORT4_STATE,
      TAG_MOXA_PORT5_STATE,
      TAG_MOXA_PORT6_STATE,
      TAG_MOXA_PORT7_STATE,
      TAG_MOXA_PORT8_STATE,
      TAG_MOXA_PORT9_STATE,
      TAG_MOXA_PORT10_STATE,
      TAG_MOXA_PORT11_STATE,
      TAG_MOXA_PORT12_STATE,
      TAG_MOXA_PORT13_STATE,
      TAG_MOXA_PORT14_STATE,
      TAG_MOXA_PORT15_STATE,
      TAG_MOXA_PORT16_STATE
    };
  }
}

#endif // SUUPORTED_SIGNAL_TAGS

