#ifndef UNIVERSAL_PACKET_TO_SIGNAL_GLOBAL_H
#define UNIVERSAL_PACKET_TO_SIGNAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNIVERSAL_PACKET_TO_SIGNAL_LIBRARY)
#  define UNIVERSAL_PACKET_TO_SIGNAL_EXPORT Q_DECL_EXPORT
#else
#  define UNIVERSAL_PACKET_TO_SIGNAL_EXPORT Q_DECL_IMPORT
#endif

#endif // PROJ_APAK_RADUGA_GLOBAL_H
