#ifndef UNIVERSAL_PACKET_GLOBAL_H
#define UNIVERSAL_PACKET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNIVERSAL_PACKET_LIBRARY)
#  define UNIVERSAL_PACKET_EXPORT Q_DECL_EXPORT
#else
#  define UNIVERSAL_PACKET_EXPORT Q_DECL_IMPORT
#endif

#endif // UNIVERSAL_PACKET_GLOBAL_H
